<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Midtrans</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>55b07172-d4ac-4a0b-8362-5c37079c7446</testSuiteGuid>
   <testCaseLink>
      <guid>92370033-8743-4f5d-aa94-07653c8e5723</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans001-Positive</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d1205fce-2385-44e8-9d24-214ae78b252c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans002-Positive</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7f02b4-3de9-4d5a-98db-769e4cdf9467</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6de3bb9d-a8bf-4aa1-af4a-323a47f0b94b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c61347c-028d-434a-afe8-79fd5fa726c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>181b5fd7-b747-4ca6-a96c-a601e673df25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db2ef3f8-60d2-4f23-9847-9c7530315b20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>017a7616-eaf4-4385-999d-32a00185d904</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>140e2043-1cfa-4a39-9b89-8a4d997f6cab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans003-Positive</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99104a92-a7da-4109-bb55-79ae2bb24ab0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1a9305e-8818-4d3a-842a-e416b539c708</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75605422-8040-4965-be2a-fcf91f343b1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d6b1cbd-015f-4cb1-ae03-b1e7e3afa92b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>052e4206-17aa-43e4-a3af-46ed72796717</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9db261d-a750-41e0-8441-373e281e6e80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2f602d9-d518-4f9f-8549-9fa6d1f863ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans004-Positive</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e085f86-b9ac-473b-9792-0939b1c82ed9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4dd19f9-687a-4d79-b4de-be5a2e375a35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24be626c-a568-4645-a305-337ac5b40228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>539fadb8-a736-4c25-aa98-d37fcb5dce4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a98429be-788a-4c7c-b069-5b149b5aef5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a1736b2-33a1-4b24-984f-5115379d1585</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c06f5a64-9c76-40ad-a725-f363b36653bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans005-Positive</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6202e0d-2b28-4460-b7cc-59aa615898e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be19e0ae-bc0e-4079-9288-dff94c8a8e05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ca92a8-767c-4f6f-8b8a-e002ae701184</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1422441c-0b25-4db8-b457-a1b5a9a51057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47c41ecf-b499-4f5b-ad93-e96745a6cdc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a860d0f-475e-4f73-987d-b872dbf7aaa1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d7d125b-ceef-4b4f-afcd-c852e2eac24c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MidTrans006-Positive</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bc65fbe2-d626-45af-a366-8a670d078877</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans009-Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36df9cf2-26e7-4dc6-ba7a-bd5999ce9ffa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a8fed7e-0f70-4691-a188-82ff05c1ccd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea393754-c6fb-46ee-a5be-37d5e32fbd3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48e51a80-578d-40c5-81f2-f76b197358f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80597af9-abfe-4bb8-b576-7cdaa7ad15d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65882740-cd52-4003-9d47-61389db389ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82a4192f-e903-4ad0-a274-bda9caf95147</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a92670cc-4fd6-4f7e-a8b9-f2ca65a20e08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f1b0a3d-db95-4b6a-b70d-2920a3066693</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a82cf71-3ec4-4257-905b-3b783463b640</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans008-Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>158f2e7c-c7f8-4c72-9fc4-99a597b3aef6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e0f0162-fce2-459c-b16b-e156313cd86a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0085b1d-6110-40b8-a7da-89d403d37985</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29aaa400-2a5f-4fc3-a6b9-032fa6510158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e2b6c9e-1115-4116-80d0-5c77060c7e53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9a0a62c-d506-44a1-bc94-2ee560ae8e6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b6e7f60-bb71-4cf5-9227-ecd888164358</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acef28be-e29d-464e-af72-a2988d2a8520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f1fa154-1de1-4c1a-86ac-b12b04ba09f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e5d92a39-3e88-49e5-b54b-ec63899618f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans007-Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>525a9426-cc66-4cc6-8e3c-6377f7931475</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>373cb2af-e45d-40e1-aeee-76726760b2f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28a4e541-97f8-4fc1-8464-cbfa3b5f8fbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dbfdb65-7759-4fd8-a3af-5e4afafef11d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4544ceb8-8f33-4c5b-88ea-401082a4adbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d93da46-9401-4096-a4bb-2fb4082a92c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6737b3a7-3110-4a40-8815-07a88b894343</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00a1ad58-738d-48f4-a276-2189ed950ee2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8042e13f-492f-4f69-9dc0-aedd0ebffbe5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f28a9c0-9d18-4e26-9835-4a5a993c7c0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans010-Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ad623c2-eb0f-4cb2-9df9-eabf79a20473</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9cf7b6d-4f65-410b-a7f4-51a4fb595d9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f35df20b-c014-4464-bbaa-8da2290df0fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d69ec5-1c28-43ea-bb05-ef0a33235610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>603bdf8c-eb8b-4149-ae24-55d75c1114a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb335335-c5d4-431b-9c7e-86428d7d182f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62efaef4-62ed-476c-9b4f-a8c8ae15a929</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>321ebee8-4d59-4a4f-a282-c21926d3ece7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6e50676-f78a-4fdf-9847-22a49e0bfa4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d22d8b3f-11ba-4081-9fb4-a4e6d71684d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Midtrans011-Negative</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5f209c5-c303-4bac-84c6-c5ed78973ace</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89c5f379-1495-4b1e-83eb-3d84c9cd6544</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2536cc04-d741-4086-8d2f-46eebb73a5ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff688b71-0f2b-4253-bb7c-e7ee2dba2df8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57c7b837-46cd-4cb4-a1d9-00d1ebd5ff51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a446cd2-dcc2-4a93-b284-d0af0a878c63</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
