<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-buy-now</name>
   <tag></tag>
   <elementGuidId>26c109ae-822a-453c-adbe-ae55b3be52c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.buy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.buy</value>
   </webElementProperties>
</WebElementEntity>
