<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-creditcard</name>
   <tag></tag>
   <elementGuidId>18c23c65-2bef-4643-9efa-8d3eb8857475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.with-promo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.with-promo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[.='Credit/Debit Card']</value>
   </webElementProperties>
</WebElementEntity>
