<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-checkout</name>
   <tag></tag>
   <elementGuidId>c6bf11a2-8ecc-4cc5-a618-59823ce0ae12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.cart-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.cart-checkout</value>
   </webElementProperties>
</WebElementEntity>
