<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-cancel</name>
   <tag></tag>
   <elementGuidId>b79b1673-db00-49c3-8a44-d01f04c86cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.cancel-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.cancel-btn</value>
   </webElementProperties>
</WebElementEntity>
