<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chx-pot-10-rupiah</name>
   <tag></tag>
   <elementGuidId>5e7003a0-9f2b-4f61-a5e2-adeb5b5a76da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='input-row']/div[1]//input[@name='promo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='input-row']/div[1]//input[@name='promo']</value>
   </webElementProperties>
</WebElementEntity>
