<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label-amount</name>
   <tag></tag>
   <elementGuidId>6f8e3ccb-5a68-4f0b-8b61-d8394e29a2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.text-amount-amount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.text-amount-amount</value>
   </webElementProperties>
</WebElementEntity>
