<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-Transaction-Succees</name>
   <tag></tag>
   <elementGuidId>024811bf-8d6d-4e12-a14d-2cdb3561d361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.text-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//script[4]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.text-bold</value>
   </webElementProperties>
</WebElementEntity>
