<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl-status-transaction</name>
   <tag></tag>
   <elementGuidId>b6fb0cc3-390b-4675-a3dc-1fa1d22259fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.trans-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.trans-status</value>
   </webElementProperties>
</WebElementEntity>
