<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-phone-number</name>
   <tag></tag>
   <elementGuidId>5cae4943-50ed-4554-bf4e-c41f399f927f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>[placeholder='+6281234567890']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>[placeholder='+6281234567890']</value>
   </webElementProperties>
</WebElementEntity>
