<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-process-failed</name>
   <tag></tag>
   <elementGuidId>4118c86b-b827-4d9d-b906-13ca889ab00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.pop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.pop</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//strong[.='Process failed']</value>
   </webElementProperties>
</WebElementEntity>
