<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt-Address</name>
   <tag></tag>
   <elementGuidId>32695df2-0bf9-4d5c-b044-5c9bb6eb25b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[.='MidPlaza 2, 4th Floor Jl.Jend.Sudirman Kav.10-11']</value>
   </webElementProperties>
</WebElementEntity>
